services:
  web:
    image: ghcr.io/beambeambeam/bmhk-2026/web:staging
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run --protocol http2
    environment:
      TUNNEL_TOKEN: ${CF_TUNNEL_TOKEN_WEB:?CF_TUNNEL_TOKEN_WEB is required}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
