services:
  discord:
    image: ghcr.io/beambeambeam/bmhk-2026/discord:main
    pull_policy: always
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN:?DISCORD_TOKEN is required}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID:?DISCORD_CLIENT_ID is required}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID:?DISCORD_GUILD_ID is required}
      SERVER_BASE_URL: ${SERVER_BASE_URL:?SERVER_BASE_URL is required}
      SERVER_API_KEY: ${SERVER_API_KEY:?SERVER_API_KEY is required}
      GLOBAL: true
    restart: unless-stopped
    volumes:
      - bmhk-2026_discord_data:/app/apps/discord/data

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run --protocol http2
    environment:
      TUNNEL_TOKEN: ${CF_TUNNEL_TOKEN_DISCORD:?CF_TUNNEL_TOKEN_DISCORD is required}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s

volumes:
  bmhk-2026_discord_data:
    name: bmhk-2026_discord_data
