services:
  discord:
    image: ghcr.io/beambeambeam/bmhk-2026/discord:main
    pull_policy: always
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN:?DISCORD_BOT_TOKEN is required}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID:?DISCORD_CLIENT_ID is required}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET:?DISCORD_CLIENT_SECRET is required}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID:?DISCORD_GUILD_ID is required}
      GLOBAL: true
    restart: unless-stopped
    volumes:
      - bmhk-2026_discord_data:/app/apps/discord/data

volumes:
  bmhk-2026_discord_data:
    name: bmhk-2026_discord_data
